language: node_js
node_js:
   - '4.5'
before_script:
   - npm install -g grunt
script:
   - grunt standards
   - npm test
# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
